### ISSUE TITLE
Error dialog remains open after successfully loading report afterwards

### ISSUE THREAD

**Issue by Marcono1234** [misode/report#2]
### Description
When you first load a report which cannot be parsed, and the error dialog appears, and then load a report which can be parsed successfully, the error dialog remains open.
(Additionally the error dialog moves when the page is scrolled, e.g. on the "Profiling" tab.)

### Reproduction steps
1. Load a report which cannot be parsed
ℹ️ The error dialog appears
2. Load a report which can be parsed
:x: The error dialog remains open

**Comment by misode** [comment]
🚀 This fix has been deployed! Thank you for reporting!

**Comment by Marcono1234** [comment]
Thank you for the fast fix!
