### ISSUE TITLE
Say "CPU cores" instead of "CPUs"

### ISSUE THREAD

**Issue by CalXee** [misode/report#5]
It would make much more sense to say cores right? I'm sure I don't have 2 CPUs lol
![Screenshot 2021-12-20 132949](https://user-images.githubusercontent.com/68349758/146815615-3c877eee-c2a8-485e-a6c9-581cc6cc02b6.png)

**Comment by misode** [comment]
CPUs is the actual name used in the files. But I guess you're right that using "cores" would be slightly more correct.
